# Generated by Django 3.2 on 2022-08-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('creado', models.DateField(auto_now_add=True)),
                ('cuerpo', models.TextField()),
                ('autor', models.CharField(blank=True, max_length=50, null=True)),
                ('imgen', models.ImageField(blank=True, null=True, upload_to='noticias')),
            ],
        ),
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
