# Generated by Django 3.2 on 2022-08-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20220809_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('decripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='imgen',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noticias.categoria'),
        ),
    ]
